"""recreate tables after reset

Revision ID: 4ab60c67647e
Revises: 66f12e587afb
Create Date: 2026-03-16 17:52:33.700659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData


# revision identifiers, used by Alembic.
revision: str = '4ab60c67647e'
down_revision: Union[str, None] = '66f12e587afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('cid', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=512), nullable=False),
    sa.Column('encryption_type', sa.Text(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_cid'), 'files', ['cid'], unique=True)
    op.create_index(op.f('ix_files_hash'), 'files', ['hash'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_owner'), 'files', ['owner'], unique=False)
    op.create_index(op.f('ix_files_upload_date'), 'files', ['upload_date'], unique=False)
    op.create_table('access_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_wallet', sa.String(length=512), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_permissions_file_id'), 'access_permissions', ['file_id'], unique=False)
    op.create_index(op.f('ix_access_permissions_id'), 'access_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_access_permissions_user_wallet'), 'access_permissions', ['user_wallet'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_wallet', sa.String(length=512), nullable=False),
    sa.Column('action', sa.Enum('UPLOAD', 'DOWNLOAD', 'SHARE', 'DELETE', 'PERMISSION_GRANT', 'PERMISSION_REVOKE', name='auditaction', metadata=MetaData()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_file_id'), 'audit_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_wallet'), 'audit_logs', ['user_wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_wallet'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_file_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_access_permissions_user_wallet'), table_name='access_permissions')
    op.drop_index(op.f('ix_access_permissions_id'), table_name='access_permissions')
    op.drop_index(op.f('ix_access_permissions_file_id'), table_name='access_permissions')
    op.drop_table('access_permissions')
    op.drop_index(op.f('ix_files_upload_date'), table_name='files')
    op.drop_index(op.f('ix_files_owner'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_hash'), table_name='files')
    op.drop_index(op.f('ix_files_cid'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
