"""add additional indexes and optimize queries

Revision ID: 6e0b7b8e6f4d
Revises: 4ab60c67647e
Create Date: 2026-03-16 18:12:43.028784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0b7b8e6f4d'
down_revision: Union[str, None] = '4ab60c67647e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
