"""add_file_keys_table

Revision ID: 95f5728b858d
Revises: 76a4843cd73f
Create Date: 2026-03-29 16:02:49.051184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f5728b858d'
down_revision: Union[str, None] = '76a4843cd73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(length=512), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_keys_file_id'), 'file_keys', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_keys_id'), 'file_keys', ['id'], unique=False)
    op.create_index(op.f('ix_file_keys_wallet'), 'file_keys', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_keys_wallet'), table_name='file_keys')
    op.drop_index(op.f('ix_file_keys_id'), table_name='file_keys')
    op.drop_index(op.f('ix_file_keys_file_id'), table_name='file_keys')
    op.drop_table('file_keys')
    # ### end Alembic commands ###
