"""Add folder_id to access and audit logs

Revision ID: ae5651777d7a
Revises: 95f5728b858d
Create Date: 2026-03-29 20:40:24.889692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5651777d7a'
down_revision: Union[str, None] = '95f5728b858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_permissions', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.alter_column('access_permissions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_access_permissions_folder_id'), 'access_permissions', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'access_permissions', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.add_column('audit_logs', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_folder_id'), 'audit_logs', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_folder_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'folder_id')
    op.drop_constraint(None, 'access_permissions', type_='foreignkey')
    op.drop_index(op.f('ix_access_permissions_folder_id'), table_name='access_permissions')
    op.alter_column('access_permissions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('access_permissions', 'folder_id')
    # ### end Alembic commands ###
